import './polyfills'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { App } from './App'
import { applyUi, cachedUi } from './ui'
import './i18n'
import './tokens.css'
// 화면별 스타일. 순서가 곧 우선순위다: 새 화면은 자기 파일을 만들어 맨 아래에 한 줄 더한다
import './styles/base.css'
import './styles/map.css'
import './styles/block.css'
import './styles/dialogs.css'
import './styles/memo.css'
import './styles/work.css'
import './styles/feedback.css'
import './styles/home.css'
import './styles/settings.css'
import './styles/about.css'
import './styles/sidebar.css'
import './styles/library.css'
import './styles/overview.css'
import './styles/pdf.css'
import './styles/info.css'
import './styles/google.css'
import './styles/cited.css'
import './styles/notes.css'
import './styles/topics.css'
import './styles/latex.css'
import './styles/concepts.css'
import './styles/settings-side.css'
import './styles/network.css'
import './styles/note-kinds.css'
import './styles/row-resizer.css'
import './styles/note-export.css'
import './styles/note-todo.css'
import './styles/rail-count.css'
import './styles/about-fix.css'
import './styles/app-info.css'
import './styles/register.css'
import './styles/search.css'
import './styles/note-markdown.css'
import './styles/manuscript.css'
import './styles/note-screen.css'
import './styles/cards.css'
import './styles/topic-screen.css'
import './styles/topic-dialog.css'
import './styles/project-profile.css'
import './styles/papers.css'
import './styles/figures.css'
import './styles/records.css'
import './styles/records-sidebar.css'
import './styles/card-image-picker.css'
import './styles/knowledge-home.css'
import './styles/library-home.css'
import './styles/knowledge-list.css'
import './styles/library-settings.css'
import './styles/subject-picker.css'
import './styles/work-tab.css'
import './styles/agent-edits.css'
import './styles/window-controls.css'

applyUi(cachedUi())

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
