// API 안내: GET /api 하나로 서버의 모든 경로와, 에이전트가 화면 대신 쓰기 좋은 대표 경로를 돌려준다
import type { FastifyInstance } from 'fastify'
import type { RouteContext } from './context.js'
import { t } from '../i18n.js'

/** 처음 보는 에이전트가 먼저 쓰면 좋은 것 (경로는 아래 routes에 실제로 있는 것만) */
const start = (): { method: string; url: string; does: string }[] => [
  { method: 'GET', url: '/api/researches', does: t('등록한 연구(프로젝트) 목록. id가 아래의 :rid. 성격 kind(research·work) · 분야 fields · 진행 상태 state(active·paused·done), 순서는 목록 순서', 'Registered projects. id is the :rid below. kind (research·work) · fields · state (active·paused·done), in list order') },
  { method: 'PATCH', url: '/api/researches/:rid', does: t('프로젝트 성격 · 분야 · 진행 상태 고치기: { kind, fields, state } 중 보낸 것만 (이 컴퓨터 설정)', 'Edit project kind · fields · state: only the ones sent of { kind, fields, state } (settings on this computer)') },
  { method: 'GET', url: '/api/researches/:rid/image', does: t('프로젝트 카드 그림 (research.yaml의 image:, figure:<그림 id> 또는 저장소 기준 경로; PATCH …/info { image }로 바꿈)', 'Project card image (research.yaml image:, figure:<figure id> or a path in the repository; change with PATCH …/info { image })') },
  { method: 'PUT', url: '/api/researches/order', does: t('프로젝트 순서 바꾸기: { ids } (홈 카드 끌기, 왼쪽 띠도 이 순서)', 'Reorder projects: { ids } (dragging Home cards; the rail uses this order too)') },
  { method: 'GET', url: '/api/researches/:rid', does: t('연구 하나의 요약: 보조 노트(블록)·진술·할 일·상태', 'Summary of one project: notes (blocks) · statements · to-dos · status') },
  { method: 'GET', url: '/api/researches/:rid/agent-rules', does: t('이 연구 저장소의 에이전트 규칙: { files: [{ file, text }] } (맨 위 AGENTS.md · CLAUDE.md)', 'Agent rules of this research repository: { files: [{ file, text }] } (top-level AGENTS.md and CLAUDE.md)') },
  { method: 'GET', url: '/api/concepts/rules', does: t('개념노트 규칙: { rules: { file, text } } (research-library README의 개념노트 절)', 'Concept note rules: { rules: { file, text } } (the concept-note section of the research-library README)') },
  { method: 'GET', url: '/api/researches/:rid/topics', does: t('주제 목록 (research.yaml topics:)과 hash', 'Topic list (research.yaml topics:) and hash') },
  { method: 'GET', url: '/api/researches/:rid/topics/overview', does: t('주제마다 노트 수(상태별)·성격·최근 시각, 주제 없는 노트("노트들")', 'Per topic: note counts (by status) · kind · last change; notes without a topic ("노트들")') },
  { method: 'PATCH', url: '/api/researches/:rid/topics/:tid', does: t('주제 고치기: title · description · preview{text,image,color} · star · done (baseHash)', 'Edit a topic: title · description · preview{text,image,color} · star · done (baseHash)') },
  { method: 'GET', url: '/api/researches/:rid/notes', does: t('노트 한 목록 (연구노트·계산 노트·보조 노트): 상태·성격·설명·주제·★·고친 때', 'One list of notes (research notes · calculation notes · block notes): status · kind · description · topics · ★ · last edited') },
  { method: 'DELETE', url: '/api/researches/:rid/blocks/:bid', does: t('보조 노트 원문 파일만 영구히 지우기: { baseHash }. 읽은 뒤 바뀌었으면 409와 currentHash. 기록 파일(comments/block-<id>.md)·다른 노트의 연결·컴파일 결과는 보존한다. 같은 id의 .md와 .tex가 함께 있으면 409로 거절한다', 'Permanently delete only the block note source file: { baseHash }. If it changed since reading, 409 with currentHash. The records file (comments/block-<id>.md), links from other notes and compile output are kept. If both .md and .tex exist for the same id, refused with 409') },
  { method: 'PATCH', url: '/api/researches/:rid/notes/head', does: t('노트 머리말 고치기: { file, patch: { title, topics, kind, description, star }, baseHash }', 'Edit a note\'s front matter: { file, patch: { title, topics, kind, description, star }, baseHash }') },
  { method: 'POST', url: '/api/researches/:rid/notes/reveal', does: t('노트 파일을 Finder에서 보이기 (맥): { file }', 'Show the note file in Finder (Mac): { file }') },
  { method: 'GET', url: '/api/researches/:rid/notes/links', does: t('노트가 쓰는 개념노트와 이 노트를 인용한 노트 (?file=)', 'Concept notes a note uses and notes that cite this note (?file=)') },
  { method: 'GET', url: '/api/researches/:rid/manuscripts', does: t('원고와 장 목록', 'Manuscripts and their chapters') },
  { method: 'GET', url: '/api/researches/:rid/comments', does: t('노트 기록 파일 목록과 대기 질문. count와 pending에는 하이라이트를 세지 않는다', 'Note records files and pending questions. count and pending do not count highlights') },
  { method: 'GET', url: '/api/researches/:rid/records', does: t('프로젝트와 모든 노트의 기록 모으기: { files: [{ target, title, source?, hash, comments }] }. project가 먼저, 나머지는 대상 이름순. 하이라이트는 제외하고 인용 위치 line은 다시 찾는다. 기록이 없는 project도 빈 목록으로 반환한다', 'Records of the project and all notes: { files: [{ target, title, source?, hash, comments }] }. project first, the rest by target name. Highlights excluded; quote position line is found again. project is returned with an empty list even without records') },
  { method: 'GET', url: '/api/researches/:rid/comments/:target', does: t('노트 기록 읽기 (target: project, manuscript, block-<id>, note-<slug>, calc-<slug>). comments에는 메모·할 일·질문, highlights에는 하이라이트를 반환한다. 예전 코멘트는 메모로 읽는다. 본문 선택은 prefix+quote+suffix, 다음 quote로 다시 찾아 line(1부터)을 맞추며, 없으면 lost:true로 남긴다. 읽을 때 파일은 고치지 않는다', 'Read note records (target: project, manuscript, block-<id>, note-<slug>, calc-<slug>). comments holds memos · to-dos · questions, highlights holds highlights. Old comments read as memos. A text selection is prefix+quote+suffix, found again by quote to set line (from 1); if not found it stays with lost:true. Reading never changes the file') },
  { method: 'POST', url: '/api/researches/:rid/comments/:target', does: t('기록 덧붙이기: { kind, title, source?, text, color?, line?, quote?, prefix?, suffix?, page?, rects? }. kind는 메모·할 일·질문·하이라이트·코멘트·자동. 코멘트는 메모, 자동은 unsorted:true인 메모로 저장. color는 yellow|green|blue|pink(하이라이트 필수). 본문 선택은 line(1부터)·quote·앞뒤 글(prefix·suffix), PDF 선택은 page(1부터)·rects([x,y,w,h], PDF 포인트·왼쪽 위 원점). 할 일은 project·note-·calc-·block- 대상에 대기로 만들고 일지 todo도 덧붙인다(project는 연구 전체, note-·calc-는 source 경로, block-는 보조 노트). 기록 meta의 journal("YYYY-MM-DD HH:MM")로 연결하며 기록 파일이 정본', 'Append a record: { kind, title, source?, text, color?, line?, quote?, prefix?, suffix?, page?, rects? }. kind is one of 메모 (memo) · 할 일 (to-do) · 질문 (question) · 하이라이트 (highlight) · 코멘트 (comment) · 자동 (auto). 코멘트 is saved as 메모, 자동 as 메모 with unsorted:true. color is yellow|green|blue|pink (required for highlights). A text selection is line (from 1) · quote · surrounding text (prefix · suffix); a PDF selection is page (from 1) · rects ([x,y,w,h], PDF points, top-left origin). A to-do is created as 대기 (waiting) on project · note- · calc- · block- targets and also appends a journal todo (project is the whole project, note- · calc- the source path, block- the block note). Linked by the record meta journal ("YYYY-MM-DD HH:MM"); the records file is the source of truth') },
  { method: 'POST', url: '/api/researches/:rid/comments/:target/classify', does: t('자동 분류: { baseHash }. 이 대상의 unsorted 기록만 Haiku에 한 번 보내 메모·할 일·질문으로 나누고 CommentFile을 반환한다. 하나면 본문을 보존해 종류만 바꾸며 여러 개면 원문에 split:true를 남기고 같은 인용·좌표·색의 기록을 덧붙인다. 할 일은 일지에도 연결한다. 응답을 기다리는 동안 바뀐 기록은 분류 전과 본문이 그대로인 것만 반영하며 답과 다른 기록은 보존한다. 분류할 기록이 없으면 400, 처음 해시가 다르거나 같은 대상이 분류 중이면 409, 모델·해석 실패는 쓰기 없이 502', 'Auto-sort: { baseHash }. Sends only this target\'s unsorted records to Haiku once, splits them into 메모 · 할 일 · 질문 and returns the CommentFile. One result keeps the text and changes only the kind; several leave split:true on the original and append records with the same quote · coordinates · color. To-dos are linked to the journal too. Records changed while waiting are updated only if their text is unchanged; answers and other records are kept. 400 if nothing to sort, 409 if the starting hash differs or the same target is being sorted, 502 with no write on model or parse failure') },
  { method: 'PATCH', url: '/api/researches/:rid/comments/:target/:id', does: t('기록의 상태·색·글 고치기: { state?, color?, text?, baseHash }. 질문 상태는 대기·답함·끝냄, 할 일은 대기·끝냄. 색은 yellow|green|blue|pink. 파일이 바뀌었으면 409와 currentHash. 글은 그 기록의 본문만 바꾸며 머리·메타·인용·상태·답과 다른 기록의 바이트를 보존한다. 할 일 상태는 연결된 일지 todo에도 반영하고, 끝낼 때 done 일지를 남긴다. 할 일 글은 연결된 일지가 예전 글과 일치할 때만 함께 바꾼다', 'Edit a record\'s state · color · text: { state?, color?, text?, baseHash }. Question states are 대기 · 답함 · 끝냄 (waiting · answered · closed), to-dos 대기 · 끝냄. color is yellow|green|blue|pink. If the file changed, 409 with currentHash. text replaces only that record\'s body and keeps the bytes of the header · meta · quote · state · answers and other records. A to-do state is applied to the linked journal todo too, and closing leaves a done journal entry. To-do text changes the linked journal entry only when it matches the old text') },
  { method: 'DELETE', url: '/api/researches/:rid/comments/:target/:id', does: t('기록·하이라이트 하나 지우기: ?baseHash=. 파일이 바뀌었으면 409와 currentHash. 다른 기록과 노트 본문은 보존한다', 'Delete one record or highlight: ?baseHash=. If the file changed, 409 with currentHash. Other records and the note body are kept') },
  { method: 'GET', url: '/api/researches/:rid/tasks', does: t('맡긴 일 (workbench/tasks/*.md, 일 하나에 파일 하나 = 보고서): 제목·상태(working·proposed·result·done·paused·stopped)·결론·사용자 확인 요청·남은 문제·다음 지시·검증·사용자 답·판단 기록. 형식은 docs/agent-delegated-work.md', 'Delegated tasks (workbench/tasks/*.md, one file per task = report): title · state (working·proposed·result·done·paused·stopped) · conclusion · review requests to the user · open issues · next instructions · checks · user answers · decision log. Format: docs/agent-delegated-work.md') },
  { method: 'POST', url: '/api/researches/:rid/tasks', does: t('맡기기: { title, task, endCondition?, topic?, agent?, references?, avoid? }. 종결 조건이 비면 에이전트가 proposal부터 적는다. 판단(…/tasks/:id/judge)·답(…/answer)·다음 지시(…/next)는 사용자가 앱에서 한다', 'Delegate: { title, task, endCondition?, topic?, agent?, references?, avoid? }. If the completion criteria are empty, the agent writes a proposal first. Decide (…/tasks/:id/judge) · answer (…/answer) · next instruction (…/next) are done by the user in the app') },
  { method: 'POST', url: '/api/researches/:rid/journal', does: t('오늘 일지에 한 줄 더하기: { kind: memo|todo, text, target? }. target은 연구 전체, 블록 id, 저장소 안 .tex 노트 경로 또는 workbench/notes/<이름>/note.md', 'Add a line to today\'s journal: { kind: memo|todo, text, target? }. target is the whole project, a block id, a .tex note path in the repository or workbench/notes/<name>/note.md') },
  { method: 'PATCH', url: '/api/researches/:rid/journal/:date/:index', does: t('일지 할 일 완료 바꾸기: { done, was } (was = 읽을 때 본 할 일 글, 그새 바뀌었으면 409). 날짜·시각·종류 todo·target·text가 일치하는 노트 기록의 journal 연결이 있으면 정본인 기록의 상태도 대기·끝냄으로 맞춘다. 끝낼 때 done 일지를 남기며 연결을 찾지 못하면 건너뛴다. 글 고치기는 { text, was }', 'Toggle a journal to-do: { done, was } (was = the to-do text seen when reading; 409 if it changed). If a note record has a journal link matching date · time · kind todo · target · text, the state of that record (the source of truth) is set to 대기 · 끝냄 as well. Closing leaves a done journal entry; a link that is not found is skipped. Edit text with { text, was }') },
  { method: 'GET', url: '/api/subjects', does: t('subjects.yaml 유무(enabled), 파일 hash, 분류 나무(id·name·parent·notes·figures·papers, 자손 포함). ?note=id는 연결 노트 빈도순 추천, 연결 없으면 자주 쓰는 분류. 나무가 없으면 기존 subject 경로 유지', 'Whether subjects.yaml exists (enabled), file hash, subject tree (id · name · parent · notes · figures · papers, descendants included). ?note=id suggests subjects by frequency among linked notes, or frequently used subjects without links. Without a tree the old subject paths stay') },
  { method: 'PATCH', url: '/api/subjects', does: t('분류 이름만 고치기: { id, name, baseHash }. 노트 파일은 그대로, 해시 충돌 409', 'Rename a subject only: { id, name, baseHash }. Note files unchanged, 409 on hash conflict') },
  { method: 'POST', url: '/api/subjects', does: t('분류 더하기: { parent, slug, name, baseHash }. parent 빈 값은 최상위, slug 영문 소문자·숫자·하이픈, 깊이 3 이하, 중복 거절', 'Add a subject: { parent, slug, name, baseHash }. Empty parent is top level, slug is lowercase letters · digits · hyphens, depth 3 or less, duplicates refused') },
  { method: 'PUT', url: '/api/concepts/:id/subjects', does: t('분류 고치기: { subjects, baseHash }. 나무에 있는 ID 1–3개, 순서 유지·첫째 주 분류, []는 분류 빼기. 본문·checked 보존. 노트 전체 hash는 GET /api/concepts/:id', 'Edit subjects: { subjects, baseHash }. 1–3 IDs from the tree, order kept, the first is the main subject, [] removes subjects. Body and checked are kept. The whole-note hash is from GET /api/concepts/:id') },
  { method: 'GET', url: '/api/figures/subjects', does: t('?id=그림 ID. 해당 figures.yaml의 hash (목록 행 subjectsHash도 같은 값)', '?id=figure ID. Hash of that figures.yaml (same as the list row subjectsHash)') },
  { method: 'PUT', url: '/api/figures/subjects', does: t('그림 분류: { id, subjects, baseHash }. 해당 figures.yaml 항목의 subjects만 고침', 'Figure subjects: { id, subjects, baseHash }. Changes only subjects of that figures.yaml entry') },
  { method: 'GET', url: '/api/papers/:key/subjects', does: t('papers.yaml의 hash (목록 행 subjectsHash도 같은 값)', 'Hash of papers.yaml (same as the list row subjectsHash)') },
  { method: 'PUT', url: '/api/papers/:key/subjects', does: t('논문 분류: { subjects, baseHash }. papers.yaml bib 키 항목의 subjects만 고침', 'Paper subjects: { subjects, baseHash }. Changes only subjects of the papers.yaml bib key entry') },
  { method: 'GET', url: '/api/concepts/list', does: t('개념노트 표 (subjectPrefix=분류 ID는 어느 subjects에든 자신·자손 포함, 빈 값은 분류 없음; 나무 없으면 기존 경로. 이상·점검 거르기, 머리말 정렬, 50개씩; 직접 쓰는 프로젝트·출처·링크·이상·고친 날)', 'Concept note table (subjectPrefix=subject ID matches itself and descendants in any subjects, empty means no subject; without a tree the old paths. Filter by issues · check, sort by front matter, 50 at a time; projects that use it directly · sources · links · issues · last edited)') },
  { method: 'GET', url: '/api/concepts/subjects', does: t('분류별 수. 나무 있으면 ID·name·parent·자손 포함 중복 없는 count·model: ids, 없으면 기존 subject 경로별 count. 빈 subject는 분류 없음', 'Counts per subject. With a tree: ID · name · parent · count without duplicates including descendants · model: ids; without one, count per old subject path. Empty subject means no subject') },
  { method: 'GET', url: '/api/concepts/brief', does: t('지식 첫 화면: total, recent(최근 고친 노트, ?recent=개수), check(연구가 쓰는 노트 = 프로젝트 노트·원고가 링크한 개념노트와 그 전제 한 단계 중 unchecked 확인 전 · changedAfterCheck 확인 뒤 바뀜, draftsToReview 초안이 다 된 공부할 것), stats(empty 비어 있음 · emptySection 빈 절 · todo TODO와 - [ ] · brokenLink 끊긴 링크 · noSource 출처 없음 · unknownCite references.bib에 없는 인용 키). 각각 count와 ids', 'Knowledge first screen: total, recent (recently edited notes, ?recent=count), check (notes the projects use = concept notes linked from project notes · manuscripts plus one step of their prerequisites: unchecked not reviewed yet · changedAfterCheck changed after review, draftsToReview things to study whose draft is done), stats (empty · emptySection empty section · todo TODO and - [ ] · brokenLink · noSource no source · unknownCite citation key not in references.bib). Each has count and ids') },
  { method: 'GET', url: '/api/concepts/search', does: t('개념노트 본문 찾기(?q=낱말 &limit=): 모든 낱말이 이름·다른 이름·본문에 든 노트(최대 limit개, 기본 20)와 hits(낱말이 있는 본문 줄 번호 line · 그 줄의 절 제목 heading · 줄 글 text, 노트마다 3개까지)', 'Search concept note text (?q=words &limit=): notes whose name, aliases or body contain every word (up to limit, default 20) with hits (body line number, the heading it falls under, the line text; up to 3 per note)') },
  { method: 'POST', url: '/api/agent-edits/write', does: t('에이전트가 노트 · 개념노트 고치기: { target: { kind: "note", rid, file } | { kind: "concept", id }, baseHash, edits: [{ old, new }], approved?, agent?, summary? }. old는 지금 글(노트는 파일 전체, 개념노트는 머리말을 뺀 본문)에 꼭 한 곳. 작업 중인 노트는 바로 쓰고 고치기 전 글을 기준판으로 남겨 사용자가 문단마다 승인 · 되돌리기 · 직접 고치기로 검토한다. 확인된 노트(개념노트 확인함 · 노트 상태 해결)는 approved 없이 428: 사용자에게 시도가 보이고, 에이전트는 대화에서 허락을 받은 뒤 approved: true로 다시 보낸다. 원고 · 잠긴 노트는 고치지 않는다', 'Agent edit of a note or concept note: { target: { kind: "note", rid, file } | { kind: "concept", id }, baseHash, edits: [{ old, new }], approved?, agent?, summary? }. Each old must occur exactly once in the current text (the whole file for notes, the body without front matter for concept notes). Notes in progress are written at once and the text before the edit is kept as a baseline, so the user reviews each paragraph: approve, revert or edit. Reviewed notes (concept notes marked reviewed, notes with status solved) get 428 without approved: the user sees the attempt; ask the user in the conversation, then send again with approved: true. Manuscripts and locked notes are not changed') },
  { method: 'GET', url: '/api/agent-edits', does: t('에이전트 고침 목록(?scope=프로젝트 id 또는 library): reviews(검토를 기다리는 노트와 바뀐 곳 수 changes) · attempts(확인된 노트 쓰기 시도)', 'Agent edits (?scope=project id or library): reviews (notes awaiting review and number of changes) · attempts (write attempts on reviewed notes)') },
  { method: 'GET', url: '/api/concepts/:id', does: t('개념노트 하나 (본문과 hash)', 'One concept note (body and hash)') },
  { method: 'GET', url: '/api/learn', does: t('공부할 것 (모름) 목록', 'Things to study (unknown) list') },
  { method: 'GET', url: '/api/papers/brief', does: t('논문 첫 화면: total, recent(최근 더한 논문 = references.bib 끝부터, ?recent=개수), check(noFolder PDF 폴더 없음 · answered 답이 온 질문 수), stats(noPdf PDF 없음 · arxiv PDF 없고 arXiv 번호 있음 · unlinked 프로젝트에 안 묶임 · papers 논문 · books 책 · unclassified 분류 없음(나무 있을 때)), folders(PDF 폴더와 cloud: icloud·drive·local)', 'Papers first screen: total, recent (recently added papers = from the end of references.bib, ?recent=count), check (noFolder no PDF folder · answered number of answered questions), stats (noPdf no PDF · arxiv no PDF but an arXiv number · unlinked not tied to a project · papers · books · unclassified no subject (with a tree)), folders (PDF folders and cloud: icloud·drive·local)') },
  { method: 'GET', url: '/api/figures/brief', does: t('그림 첫 화면: total, recent(최근 더한 그림 = 파일 시각 순, ?recent=개수), check(broken 그림으로 못 바꾼 tikz), stats(tikz · svg · photo png·jpg · pdf · unused 쓰는 노트 없음 · unclassified 분류 없음(나무 있을 때)), store(library 공용 수 · projects 그림 있는 프로젝트 수 · inProjects 프로젝트 전용 수)', 'Figures first screen: total, recent (recently added figures = by file time, ?recent=count), check (broken tikz that could not be drawn), stats (tikz · svg · photo png·jpg · pdf · unused no note uses it · unclassified no subject (with a tree)), store (library shared count · projects projects with figures · inProjects project-only count)') },
  { method: 'GET', url: '/api/figures', does: t('그림 라이브러리: 공용(research-library/figures)과 프로젝트 전용(workbench/figures) 그림, 그림마다 쓰는 노트. ?subjectPrefix=ID로 자손 포함 거르기(빈 값은 분류 없음), brief도 같은 거르기. 논문 목록·brief도 같음. 노트에는 ![[이름]]으로 넣는다', 'Figure library: shared (research-library/figures) and project-only (workbench/figures) figures, with the notes using each. ?subjectPrefix=ID filters including descendants (empty means no subject); brief filters the same. The paper list and brief do too. Put a figure in a note with ![[name]]') },
]

export function registerApiIndex(app: FastifyInstance, _ctx: RouteContext): void {
  const routes: { method: string; url: string }[] = []
  // 이 뒤에 등록되는 경로를 모은다 (app.ts에서 맨 먼저 부른다)
  app.addHook('onRoute', (r) => {
    if (!r.url.startsWith('/api')) return
    for (const m of [r.method].flat()) if (m !== 'HEAD') routes.push({ method: m, url: r.url })
  })
  app.get('/api', async () => ({
    about: t('연구 작업대 서버. 화면이 하는 일은 모두 이 JSON API로도 할 수 있다. 저장소 파일이 정본이고 API는 그 파일을 읽고 쓴다.', 'Emergence Workbench server. Everything the screen does can also be done with this JSON API. Repository files are the source of truth; the API reads and writes them.'),
    writes: t('고치는 요청(PUT 등)은 읽을 때 받은 hash를 baseHash로 함께 보낸다(없으면 400). 그 사이 바깥(사람·다른 에이전트)에서 파일이 바뀌었으면 409로 거절되니 다시 읽고 고친다.', 'Requests that edit (PUT etc.) send the hash received when reading as baseHash (400 without it). If the file changed outside in the meantime (a person or another agent), the request is refused with 409: read again, then edit.'),
    start: start(),
    routes: [...routes].sort((a, b) => a.url.localeCompare(b.url) || a.method.localeCompare(b.method)),
  }))
}
